### ISSUE TITLE
Obcas je spatny status na objednavacim tlacitku u jidla - nelze zrusit

### ISSUE THREAD

**Issue by mattheroit** [Autojidelna/autojidelna#60]
Obcas pri prvnim loadu jidelnicku jsou nejake jidla v budoucnu uzavrene, soft refresh opravi chybu

Expected:
![Screenshot_20231204_114820](https://github.com/Autojidelna/autojidelna/assets/68871166/cc65479a-7115-4f33-9b13-d98c7cf9c50b)

Actual:
![actual](https://github.com/Autojidelna/autojidelna/assets/68871166/395f0e03-16e9-46ae-8260-e752ea50f0fe)

**Comment by tpkowastaken** [comment]
vyřešeno v branchi canteenlib 4.0.0
