### ISSUE TITLE
Problém s přihlášením 

### ISSUE THREAD

**Issue by lksmasin** [Autojidelna/autojidelna#74]
Říká to že ta URL je neplatná já bych řekl že docela funguje, ale pravděpodobně problém bude někde jinde protože nefunguje ani oficiální aplikace. Taky hlásí že chybná adresa. 
![Screenshot](https://github.com/Autojidelna/autojidelna/assets/83969712/b63b0eee-540c-4367-998b-d7113a256a39)

**Comment by tpkowastaken** [comment]
Zdravím, děkujeme za issue.

S verzí 2.16.15 (Verze vaší url) jsme se zatím nesetkali a nemáme k ní přístupové údaje tudíž není podporovaná. zde nabízím možnosti, jak tuto verzi přidat do podpory:
1. Zaslat přihlašovací údaje na tom@tomprotiva.com (Nejrychlejší)
2. Zaslat na stejnou adresu přihlašovací post request jquery v network tabu prohlížeče a následně soubor html ve kterém jsou zapsány obědy (také v network tabu) toto je ve chromu potřeba zkopírovat jako powershell a dále zaslat response
3. Nainstalovat si programovací jazyk dart a vyzkoušet danou url v knihovně [canteenlib](https://github.com/Autojidelna/canteenlib) a následně zaslat chybovou hlášku do issue v této knihovně
4. Funkční post request do knihovny [canteenlib](https://github.com/Autojidelna/canteenlib)


Ps: pokud se rozhodnete pro možnost 1 doporučuji po dobu přidávání podpory změnit heslo, a poskytnout nám to změněné. Po skončení této fáze si heslo změníte zpět

**Comment by lksmasin** [comment]
Dobře, zaslal jsem Vám email s přihlašovacími údaji. Děkuji.

**Comment by tpkowastaken** [comment]
Zdravím,
zdá se, že došlo k chybě při doručování emailu. Zkuste to ještě na protitom@gmail.com.
Díky a přeji hezký den
Tom Protiva

**Comment by lksmasin** [comment]
Dobře, odesláno. Děkuji.

**Comment by tpkowastaken** [comment]
Chyba opravena ve verzi 1.3.1
